name: discord_colour_mention_bot
description: A small Discord bot that displays the colour of messages that contain a colour code
version: 1.0.0
repository: https://github.com/TechnicJelle/DiscordColourMentionBot

environment:
  sdk: ^3.10.4

dependencies:
  image: ^4.7.2
  nyxx: ^6.7.0
  nyxx_commands: ^6.0.5

dev_dependencies:
  very_good_analysis: ^10.0.0
